/**
 * printedItemSystem.ts
 *
 * Manages game objects generated by the in-bunker 3D printer.
 * Each printed item is a fully interactive Three.js object that the player
 * can walk up to, inspect, and pick up.
 *
 * Item lifecycle:
 *   1. Player types a description in the PrinterModal → API generates mesh code + metadata
 *   2. The mesh is constructed from the returned code and placed near the printer
 *   3. The item floats and rotates, emitting a soft glow to be visible
 *   4. Player walks within PICKUP_RADIUS and presses [E] → item is picked up
 *   5. Picked-up item is applied based on its type (weapon, consumable, tool, decorative)
 */

import * as THREE from "three";

// ─── Constants ────────────────────────────────────────────────────────────────

/** Radius within which the player can pick up a printed item. */
export const PRINTED_ITEM_PICKUP_RADIUS = 2.0;

/** Y height above the floor at which printed items hover. */
const HOVER_HEIGHT = 0.65;

/** Rotation speed (radians/second). */
const ROTATION_SPEED = 1.2;

/** Hover oscillation amplitude. */
const HOVER_AMP = 0.08;

/** Hover oscillation frequency. */
const HOVER_FREQ = 1.8;

// ─── Types ────────────────────────────────────────────────────────────────────

export type PrintedItemType = "weapon" | "tool" | "consumable" | "decorative";

export interface PrintedItemMetadata {
  /** Display name of the item. */
  name: string;
  /** Short description. */
  description: string;
  /** Gameplay category that determines how the item is used. */
  type: PrintedItemType;
  /** Damage dealt when used as a weapon (0 for non-weapons). */
  damage: number;
  /** Healing amount when used as a consumable (0 for non-consumables). */
  healing: number;
  /** Scale factor applied to the generated mesh. */
  scale: number;
  /** Additional properties (e.g. range, speed, effect name). */
  properties: Record<string, unknown>;
}

export interface PrintedItemData {
  /** Unique identifier. */
  id: string;
  /** Three.js group rendered in the scene. */
  mesh: THREE.Group;
  /** World X position (at the time of placement). */
  worldX: number;
  /** World Y position (floor level). */
  worldY: number;
  /** World Z position. */
  worldZ: number;
  /** Item metadata returned by the AI. */
  metadata: PrintedItemMetadata;
  /** Current hover phase for oscillation animation. */
  hoverPhase: number;
  /** Whether the item has been picked up. */
  pickedUp: boolean;
  /** Point light giving the item a soft glow. */
  glowLight: THREE.PointLight;
  /** Outer glow ring mesh (emissive torus). */
  glowRing: THREE.Mesh;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Returns a colour for the glow based on item type.
 */
function glowColorForType(type: PrintedItemType): number {
  switch (type) {
    case "weapon":     return 0xff4422;
    case "tool":       return 0xffcc00;
    case "consumable": return 0x44ff88;
    case "decorative": return 0x8888ff;
  }
}

/**
 * Builds a simple fallback mesh when the AI-generated code fails to execute.
 * Renders as a colour-coded icosahedron so the item is still visible.
 */
export function buildFallbackMesh(type: PrintedItemType): THREE.Group {
  const group = new THREE.Group();
  const color = glowColorForType(type);
  const geo = new THREE.IcosahedronGeometry(0.2, 1);
  const mat = new THREE.MeshStandardMaterial({
    color,
    emissive: new THREE.Color(color),
    emissiveIntensity: 0.4,
    roughness: 0.5,
    metalness: 0.3,
  });
  const mesh = new THREE.Mesh(geo, mat);
  group.add(mesh);
  return group;
}

/**
 * Safely executes AI-generated mesh code.
 *
 * The code is expected to be a function body (not a full function declaration)
 * that receives `THREE` as a parameter and **returns** a `THREE.Group`.
 *
 * @param meshCode  JavaScript function body string from the AI.
 * @param THREE_ns  The Three.js namespace object.
 * @returns The constructed THREE.Group, or null on failure.
 */
export function executeGeneratedMeshCode(
  meshCode: string,
  THREE_ns: typeof THREE
): THREE.Group | null {
  try {
    // Wrap code in a function and execute it with THREE as the only dependency.
    // eslint-disable-next-line @typescript-eslint/no-implied-eval, no-new-func
    const fn = new Function("THREE", meshCode);
    const result = fn(THREE_ns);
    if (result instanceof THREE.Group) return result;
    if (result instanceof THREE.Mesh) {
      const g = new THREE.Group();
      g.add(result);
      return g;
    }
    return null;
  } catch {
    return null;
  }
}

// ─── Factory ──────────────────────────────────────────────────────────────────

/**
 * Creates a new PrintedItemData and adds its Three.js objects to the scene.
 *
 * @param scene     The Three.js scene to add objects to.
 * @param worldX    World X position to place the item.
 * @param worldY    Floor Y at the placement position.
 * @param worldZ    World Z position to place the item.
 * @param meshCode  AI-generated mesh code (function body).
 * @param metadata  Item metadata from the AI.
 * @returns The new PrintedItemData object.
 */
export function createPrintedItem(
  scene: THREE.Scene,
  worldX: number,
  worldY: number,
  worldZ: number,
  meshCode: string,
  metadata: PrintedItemMetadata,
): PrintedItemData {
  const id = `printed_${Date.now()}_${Math.random().toString(36).slice(2, 7)}`;

  // ── Build mesh ──────────────────────────────────────────────────────────────
  let itemGroup = executeGeneratedMeshCode(meshCode, THREE);
  if (!itemGroup) {
    itemGroup = buildFallbackMesh(metadata.type);
  }

  // Apply scale from metadata
  const s = Math.max(0.1, Math.min(3.0, metadata.scale || 1.0));
  itemGroup.scale.setScalar(s);

  // ── Glow ring (torus on floor) ──────────────────────────────────────────────
  const glowColor = glowColorForType(metadata.type);
  const ringGeo = new THREE.TorusGeometry(0.22, 0.03, 8, 24);
  const ringMat = new THREE.MeshStandardMaterial({
    color: glowColor,
    emissive: new THREE.Color(glowColor),
    emissiveIntensity: 1.5,
    roughness: 0.2,
  });
  const glowRing = new THREE.Mesh(ringGeo, ringMat) as THREE.Mesh;
  glowRing.rotation.x = -Math.PI / 2;
  glowRing.position.set(worldX, worldY + 0.02, worldZ);
  scene.add(glowRing);

  // ── Point light ────────────────────────────────────────────────────────────
  const glowLight = new THREE.PointLight(glowColor, 5, 5);
  glowLight.position.set(worldX, worldY + HOVER_HEIGHT + 0.3, worldZ);
  scene.add(glowLight);

  // ── Position item group ────────────────────────────────────────────────────
  itemGroup.position.set(worldX, worldY + HOVER_HEIGHT, worldZ);
  scene.add(itemGroup);

  return {
    id,
    mesh: itemGroup,
    worldX,
    worldY,
    worldZ,
    metadata,
    hoverPhase: Math.random() * Math.PI * 2,
    pickedUp: false,
    glowLight,
    glowRing,
  };
}

// ─── Per-frame Update ─────────────────────────────────────────────────────────

/**
 * Updates all printed items — hover animation, rotation, glow pulsing.
 * Call once per animation frame from the game loop.
 *
 * @param items  Array of PrintedItemData managed by Game3D.
 * @param dt     Delta time in seconds.
 * @param elapsed Total elapsed time in seconds.
 */
export function updatePrintedItems(
  items: PrintedItemData[],
  dt: number,
  elapsed: number,
): void {
  for (const item of items) {
    if (item.pickedUp) continue;

    // Hover oscillation
    item.hoverPhase += dt * HOVER_FREQ;
    const hoverY = item.worldY + HOVER_HEIGHT + Math.sin(item.hoverPhase) * HOVER_AMP;
    item.mesh.position.y = hoverY;

    // Rotation
    item.mesh.rotation.y += dt * ROTATION_SPEED;

    // Glow light pulsing
    item.glowLight.position.y = hoverY + 0.3;
    item.glowLight.intensity = 4.5 + Math.sin(elapsed * 2.5 + item.hoverPhase) * 1.5;

    // Glow ring slow rotation
    item.glowRing.rotation.z += dt * 0.4;
  }
}

// ─── Pickup ───────────────────────────────────────────────────────────────────

/**
 * Removes a printed item from the scene and marks it as picked up.
 *
 * @param scene  The Three.js scene.
 * @param item   The item to pick up.
 */
export function pickupPrintedItem(scene: THREE.Scene, item: PrintedItemData): void {
  item.pickedUp = true;
  scene.remove(item.mesh);
  scene.remove(item.glowLight);
  scene.remove(item.glowRing);
}

// ─── Proximity Check ──────────────────────────────────────────────────────────

/**
 * Returns the index of the nearest unpicked printed item within PICKUP_RADIUS
 * of the given world position, or -1 if none.
 */
export function findNearestPrintedItem(
  items: PrintedItemData[],
  px: number,
  pz: number,
): number {
  let nearestIdx = -1;
  let nearestDist = PRINTED_ITEM_PICKUP_RADIUS;

  items.forEach((item, idx) => {
    if (item.pickedUp) return;
    const dx = px - item.worldX;
    const dz = pz - item.worldZ;
    const dist = Math.sqrt(dx * dx + dz * dz);
    if (dist < nearestDist) {
      nearestDist = dist;
      nearestIdx = idx;
    }
  });

  return nearestIdx;
}
